### PR TITLE
L5.3 Fix

### PR DESCRIPTION
**Pull request by ahme-d**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this won't actually fix it. I'll be prepping a full fix soon.

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Bus/pull/8 should be the real deal. :)

**Comment by GrahamCampbell** [comment]
Will work properly for queued commands.

**Comment by ahme-d** [comment]
@GrahamCampbell  Awesome, thanks.

**Pull request closed without merging**
